<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>uk.ac.kcl.mdeo</groupId>


    <artifactId>uk.ac.kcl.mdeoptimise.lib</artifactId>
    <packaging>pom</packaging>
    <version>1.0.0</version>
    <properties>
    	<henshin_version>1.4.0.201611301251</henshin_version>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.reficio</groupId>
                <artifactId>p2-maven-plugin</artifactId>
                <version>2.1.0</version>
                <executions>
                    <execution>
                        <id>default-cli</id>
			<!-- Documentation: -->
                        <configuration>
            		<artifacts>
                       		<artifact>
                       			<id>org.mockito:mockito-core:2.19.0</id>
				</artifact>
            			<artifact>
            				<id>org.mockito:mockito-all:1.9.5</id>
            			</artifact>
                		<artifact>
				    <id>org.moeaframework:moeaframework:2.12</id>
                                </artifact>
				<artifact>
				    <id>com.google.code.gson:gson:2.8.0</id>
                                </artifact>
				<artifact>
				    <id>com.github.mifmif:generex:1.0.2</id>
				</artifact>
				<artifact>
				    <id>net.sf.supercsv:super-csv:2.4.0</id>
				</artifact>
				<artifact>
				    <id>org.apache.qpid:qpid-jms-client:0.27.0</id>
				</artifact>
				<artifact>
				    <id>org.apache.geronimo.specs:geronimo-jms_1.1_spec:1.1.1</id>
				</artifact>
				<artifact>
				    <id>org.hamcrest:java-hamcrest:2.0.0.0</id>
				</artifact>
				<artifact>
				    <id>org.json:json:20140107</id>
				</artifact>
				<artifact>
				    <id>commons-cli:commons-cli:1.4</id>
				</artifact>
            		</artifacts>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <pluginRepositories>
        <pluginRepository>
            <id>reficio</id>
            <url>https://repo.reficio.org/maven/</url>
        </pluginRepository>
    </pluginRepositories>

</project>
